INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (1, 'AS', 'USA (AMERICAN SAMOA)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (2, 'AU', 'AUSTRALIA', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (3, 'CK', 'COOK ISLANDS', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (4, 'CN', 'CHINA', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (5, 'FJ', 'FIJI', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (6, 'FM', 'FEDERATED STATES OF MICRONESIA', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (7, 'GL', 'GILBERT ISLANDS (KIRIBATI)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (8, 'GU', 'USA (GUAM)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (9, 'H4', 'International waters between Tuvalu, Phoenix and Tokelau, from the equator down to 10°S and east of 175°E to 170°W', 'BROWN', 'HS');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (10, 'H5', 'International waters between Phoenix and Line Groups, from the equator down to 10°S, east of 170°W to 155°W (excludes IW between CK and PF = Area \"I9\")', 'IRIDESCENT GREEN', 'HS');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (11, 'HB', 'USA (HOWLAND AND BAKER)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (12, 'HW', 'USA (HAWAII)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (13, 'I1', 'Doughnut hole between PNG and FSM', 'BLUE', 'HS');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (14, 'I2', 'Doughnut hole between FSM, Solomons, Kiribati, Marshall Is. Nauru, Tuvalu', 'RED', 'HS');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (15, 'I3', 'International waters east of the Philippines to Guam, above FSM, around Marshalls, up to 20°N and west of 175°E (not including areas I1, I2 and I8)', 'DARK GREEN', 'HS');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (16, 'I4', 'International waters east of Marshall Islands and Kiribati, from the equator up to 20°N and east of 175°E to 170°W', 'ORANGE', 'HS');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (17, 'I5', 'International waters around Line Group from the equator up to 20°N, east of 170°W to 150°W, and south of the equator to 20°S from 155°W-130°W', 'CRIMSON', 'HS');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (18, 'I6', 'The reminder of International waters not covered above in the Northern hemisphere of the WCP-CA', 'LIGHT BLUE', 'HS');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (19, 'I7', 'The reminder of International waters not covered above in the Southern hemisphere of the WCP-CA', 'LIGHT GREEN', 'HS');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (20, 'I8', 'International waters bordered by Fiji, Solomon Is and Vanuatu', 'PURPLE', 'HS');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (21, 'I9', 'International waters between the Cook Islands and French Polynesia', 'YELLOW', 'HS');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (22, 'ID', 'INDONESIA', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (23, 'JP', 'JAPAN', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (24, 'JT', 'USA (JOHNSTON)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (25, 'JV', 'USA (JARVIS)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (26, 'KI', 'KIRIBATI', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (27, 'KR', 'REPUBLIC OF KOREA', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (28, 'LN', 'LINE ISLANDS (KIRIBATI)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (29, 'MA', 'MATTHEW AND HUNTER (DISPUTED: FR & VU)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (30, 'MH', 'MARSHALL ISLANDS', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (31, 'MP', 'NORTHERN MARIANA ISLANDS', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (32, 'NC', 'FRANCE (NEW CALEDONIA)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (33, 'NF', 'NORFOLK (AUSTRALIA)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (34, 'NR', 'NAURU', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (35, 'NU', 'NIUE', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (36, 'NZ', 'NEW ZEALAND', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (37, 'PF', 'FRANCE (FRENCH POLYNESIA)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (38, 'PG', 'PAPUA NEW GUINEA', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (39, 'PH', 'PHILIPPINES', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (40, 'PN', 'PITCAIRN', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (41, 'PW', 'PALAU', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (42, 'PX', 'PHOENIX (KIRIBATI)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (43, 'PY', 'USA (PALMYRA)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (44, 'SB', 'SOLOMON ISLANDS', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (45, 'TK', 'TOKELAU', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (46, 'TO', 'TONGA', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (47, 'TV', 'TUVALU', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (48, 'TW', 'CHINESE TAIPEI', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (49, 'US', 'UNITED STATES OF AMERICA', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (50, 'VU', 'VANUATU', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (51, 'WF', 'FRANCE (WALLIS AND FUTUNA)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (52, 'WK', 'USA (WAKE)', '', 'EZ');
INSERT INTO `authorised_fishing_areas` (`id`, `Code`, `Description`, `Color`, `Area_Type`) VALUES (53, 'WS', 'SAMOA', '', 'EZ');
