INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (0, 'VMS', 'FFA', 'FFA VMS', NULL, 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1, 'VMS', 'WCPFC', 'Pacific VMS', NULL, 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (2, 'VMS', 'PNG', 'Papua New Guinea VMS', NULL, 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (3, 'VMS', 'KIR', 'Kiribati VMS', NULL, 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (4, 'VMS', 'TON', 'Tonga VMS', NULL, 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (5, 'VMS', 'CKI', 'Cook Islands VMS', NULL, 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (6, 'VMS', 'SOL', 'Solomon Islands VMS', NULL, 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (8, 'VMS', 'VAN', 'Vanuatu Flag VMS', NULL, 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (9, 'VMS', 'AIS', 'AIS', '', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (11, 'VMS', 'AIS2', 'AIS', '', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (100, 'CON', 'SYSTEM', 'System Testing', 'XS', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (101, 'CON', 'USCG', 'US Coast Guard', 'US', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (102, 'CON', 'FANC', 'French Armies New Caledonia', 'FR', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (103, 'CON', 'BPC', 'Australian Border Protection Command', 'AU', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (104, 'CON', 'RAAF', 'Royal Australian Airforce', 'AU', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (105, 'CON', 'RNZAF', 'New Zealand Airforce', 'NZ', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (106, 'CON', 'FAFP', 'French Armies French Polynesia', 'FR', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (107, 'CON', 'RNZN', 'New Zealand Navy', 'NZ', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (108, 'CON', 'RAN', 'Australian Navy', 'AU', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (109, 'CON', 'USN', 'US Navy', 'US', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (110, 'CON', 'USAF', 'US Airforce', 'US', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (111, 'CON', 'KI M', 'Kiribati Maritime Police', 'KI', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (112, 'CON', 'TV M', 'Tuvalu Maritime Police', 'TV', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (113, 'CON', 'FM M', 'FSM Maritime Police', 'FM', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (114, 'CON', 'RSIPF', 'Solomon Islands Maritime Police', 'SB', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (115, 'CON', 'CK M', 'Cook Islands Maritime Police', 'CK', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (116, 'CON', 'VU M', 'Vanuatu Maritime Police', 'VU', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (117, 'CON', 'FJ M', 'Fiji Navy', 'FJ', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (118, 'CON', 'TDS', 'Tonga Navy', 'TO', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (119, 'CON', 'PGNSCC', 'PNG Navy', 'PG', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (120, 'CON', 'PW M', 'Palau Maritime Law Enforcement', 'PW', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (121, 'CON', 'MH M', 'Marshall Islands Sea Patrol', 'MH', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (122, 'CON', 'KI F', 'Kiribati Fisheries', 'KI', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (123, 'CON', 'TV F', 'Tuvalu Fisheries', 'TV', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (124, 'CON', 'NORMA', 'FSM Fisheries', 'FM', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (125, 'CON', 'CIMMR', 'Cook Islands Fisheries', 'CK', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (126, 'CON', 'SB F', 'Solomon Islands Fisheries', 'SB', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (127, 'CON', 'VU F', 'Vanuatu Fisheries', 'VU', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (128, 'CON', 'FJ F', 'Fiji Fisheries', 'FJ', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (129, 'CON', 'TO F', 'Tonga Fisheries', 'TO', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (130, 'CON', 'PG NFA', 'PNG Fisheries Authority', 'PG', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (131, 'CON', 'PW F', 'Palau Fisheries', 'PW', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (132, 'CON', 'MH F', 'Marshall Islands MIMRA', 'MH', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (133, 'CON', 'NR F', 'Nauru Fisheries', 'NR', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (134, 'CON', 'TK F', 'Tokelau Fisheries', 'TK', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (135, 'CON', 'NU F', 'Niue Fisheries', 'NU', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (136, 'CON', 'FFA', 'Forum Fisheries Agency', 'XF', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (137, 'CON', 'WS M', 'Samoa Maritime Police', 'WS', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (138, 'CON', 'WS F', 'Samoa Fisheries', 'WS', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (139, 'CON', 'NOAA', 'NOAA', 'US', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (140, 'CON', 'FFA S', 'FFA Steve', 'XF', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (141, 'CON', 'FFA D', 'FFA Daniel', 'XF', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (145, 'CON', 'CPSAS', 'CPSAS', 'AU', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (146, 'CON', 'SOL-N', 'Solomon Islands Fisheries Noro', 'SB', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (800, 'CON', 'GRN', 'Greenpeace', 'XX', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (801, 'CON', 'WCPFC', 'WCPFC', 'XW', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (999, 'CON', 'OTHER', 'Other', 'XX', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1000, 'VES', 'FFA', 'FFA Vessel Register', 'XF', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1001, 'VES', 'WCPFC', 'WCPFC RFV', 'XW', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1022, 'VES', 'KIR', 'Kiribati Fisheries', 'KI', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1023, 'VES', 'TUV', 'Tuvalu Fisheries', 'TV', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1024, 'VES', 'FSM', 'FSM Fisheries', 'FM', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1025, 'VES', 'CKI', 'Cook Islands Fisheries', 'CK', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1026, 'VES', 'SOL', 'Solomon Islands Fisheries', 'SB', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1028, 'VES', 'FJ', 'Fiji Fisheries', 'FJ', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1029, 'VES', 'TO', 'Tonga Fisheries', 'TO', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1030, 'VES', 'PG', 'PNG Fisheries Authority', 'PG', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1031, 'VES', 'PW', 'Palau Fisheries', 'PW', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1032, 'VES', 'MH', 'Marshall Islands MIMRA', 'MH', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1033, 'VES', 'NAU', 'Nauru Fisheries', 'NR', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1034, 'VES', 'TK', 'Tokelau Fisheries', 'TK', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1035, 'VES', 'NU', 'Niue Fisheries', 'NU', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1038, 'VES', 'WS', 'Samoa Fisheries', 'WS', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1039, 'VES', 'VU', 'Vanuatu Fisheries', 'VU', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1101, 'VES', 'CCAMLR', 'CCAMLR', 'XA', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1102, 'VES', 'IOTC', 'IOTC', 'XI', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1103, 'VES', 'ICCAT', 'ICCAT', 'XC', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1104, 'VES', 'IATTC', 'IATTC', 'XT', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1105, 'VES', 'PTCCC', 'PTCCC', 'XB', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1106, 'VES', 'UST', 'US Treaty', 'XU', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1107, 'VES', 'FSMA', 'FSM Arrangement', 'XP', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1108, 'VES', 'CCSBT', 'CCSBT', 'XS', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1200, 'VES', 'FAO', 'Food and Argiculture Organisation', 'XF', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1210, 'VES', 'TUNA', 'Tuna.org', 'XO', 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (1800, 'VES', 'GRN', 'Greenpeace', NULL, 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (2000, 'ACT', 'PUBLIC', 'Public', NULL, 0);
INSERT INTO `source` (`source_id`, `group_name`, `type_name`, `details`, `cty_code`, `sort_order`) VALUES (2001, 'ACT', 'OBS', 'Observer', NULL, 0);
