INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('1', 'Freshwater fishes', 'Freshwater fishes', '16');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('11', 'Carps, barbels and other cyprinids', 'Freshwater fishes', '5');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('12', 'Tilapias and other cichlids', 'Freshwater fishes', '56');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('13', 'Miscellaneous freshwater fishes', 'Freshwater fishes', '35');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('2', 'Diadromous fishes', 'Diadromous fishes', '12');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('21', 'Sturgeons, paddlefishes', 'Diadromous fishes', '55');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('22', 'River eels', 'Diadromous fishes', '44');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('23', 'Salmons, trouts, smelts', 'Diadromous fishes', '45');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('24', 'Shads', 'Diadromous fishes', '49');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('25', 'Miscellaneous diadromous fishes', 'Diadromous fishes', '34');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('3', 'Marine fishes', 'Marine fishes', '25');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('31', 'Flounders, halibuts, soles', 'Marine fishes', '14');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('32', 'Cods, hakes, haddocks', 'Marine fishes', '7');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('33', 'Miscellaneous coastal fishes', 'Marine fishes', '32');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('34', 'Miscellaneous demersal fishes', 'Marine fishes', '33');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('35', 'Herrings, sardines, anchovies', 'Marine fishes', '20');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('36', 'Tunas, bonitos, billfishes', 'Marine fishes', '57');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('37', 'Miscellaneous pelagic fishes', 'Marine fishes', '38');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('38', 'Sharks, rays, chimaeras', 'Marine fishes', '50');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('39', 'Marine fishes not identified', 'Marine fishes', '26');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('4', 'Crustaceans', 'Crustaceans', '11');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('41', 'Freshwater crustaceans', 'Crustaceans', '15');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('42', 'Crabs, sea-spiders', 'Crustaceans', '9');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('43', 'Lobsters, spiny-rock lobsters', 'Crustaceans', '24');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('44', 'King crabs, squat-lobsters', 'Crustaceans', '22');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('45', 'Shrimps, prawns', 'Crustaceans', '51');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('46', 'Krill, planktonic crustaceans', 'Crustaceans', '23');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('47', 'Miscellaneous marine crustaceans', 'Crustaceans', '36');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('5', 'Molluscs', 'Molluscs', '39');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('51', 'Freshwater molluscs', 'Molluscs', '17');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('52', 'Abalones, winkles, conchs', 'Molluscs', '1');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('53', 'Oysters', 'Molluscs', '41');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('54', 'Mussels', 'Molluscs', '40');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('55', 'Scallops, pectens', 'Molluscs', '46');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('56', 'Clams, cockles, arkshells', 'Molluscs', '6');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('57', 'Squids, cuttlefishes, octopuses', 'Molluscs', '54');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('58', 'Miscellaneous marine molluscs', 'Molluscs', '37');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('6', 'Whales, seals and other aquatic mammals', 'Whales, seals and other aquatic mammals', '59');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('61', 'Blue-whales, fin-whales', 'Whales, seals and other aquatic mammals', '3');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('62', 'Sperm-whales, pilot-whales', 'Whales, seals and other aquatic mammals', '52');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('63', 'Eared seals, hair seals, walruses', 'Whales, seals and other aquatic mammals', '13');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('64', 'Miscellaneous aquatic mammals', 'Whales, seals and other aquatic mammals', '30');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('7', 'Miscellaneous aquatic animals', 'Miscellaneous aquatic animals', '28');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('71', 'Frogs and other amphibians', 'Miscellaneous aquatic animals', '18');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('72', 'Turtles', 'Miscellaneous aquatic animals', '58');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('73', 'Crocodiles and alligators', 'Miscellaneous aquatic animals', '10');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('74', 'Sea-squirts and other tunicates', 'Miscellaneous aquatic animals', '47');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('75', 'Horseshoe crabs and other arachnoids', 'Miscellaneous aquatic animals', '21');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('76', 'Sea-urchins and other echinoderms', 'Miscellaneous aquatic animals', '48');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('77', 'Miscellaneous aquatic invertebrates', 'Miscellaneous aquatic animals', '29');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('8', 'Miscellaneous aquatic animal products', 'Miscellaneous aquatic animal products', '27');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('81', 'Pearls, mother-of-pearl, shells', 'Miscellaneous aquatic animal products', '42');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('82', 'Corals', 'Miscellaneous aquatic animal products', '8');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('83', 'Sponges', 'Miscellaneous aquatic animal products', '53');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('9', 'Aquatic plants', 'Aquatic plants', '2');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('91', 'Brown seaweeds', 'Aquatic plants', '4');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('92', 'Red seaweeds', 'Aquatic plants', '43');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('93', 'Green seaweeds', 'Aquatic plants', '19');
INSERT INTO `species_aquatic_animals_and_plants` (`Code`, `Species`, `Species Group`, `Order`) VALUES ('94', 'Miscellaneous aquatic plants', 'Aquatic plants', '31');
