INSERT INTO `units_of_measurement` (`id`, `name`, `kind_of_quantity`, `print`, `cs`, `ci`, `M`, `definition_value`, `definition_unit`, `IMS_name`, `IMS_code`) VALUES (1, 'kilolitres', 'volume', 'kl', '	kl', 'KL', 'yes', '1 × 10^3', 'kl', 'kilolitres', 'kl');
INSERT INTO `units_of_measurement` (`id`, `name`, `kind_of_quantity`, `print`, `cs`, `ci`, `M`, `definition_value`, `definition_unit`, `IMS_name`, `IMS_code`) VALUES (2, 'gallon', 'volume ', 'gal', '[gal_br]', '[GAL_BR]', 'no', '4.54609 ', 'l', 'gallons', 'gl');
INSERT INTO `units_of_measurement` (`id`, `name`, `kind_of_quantity`, `print`, `cs`, `ci`, `M`, `definition_value`, `definition_unit`, `IMS_name`, `IMS_code`) VALUES (3, 'meter', 'length', 'm', 'm', 'M', 'yes', '', NULL, 'Meters', 'm');
INSERT INTO `units_of_measurement` (`id`, `name`, `kind_of_quantity`, `print`, `cs`, `ci`, `M`, `definition_value`, `definition_unit`, `IMS_name`, `IMS_code`) VALUES (4, 'foot', 'length', 'ft', '[ft_br]', '[FT_BR]', 'no', '12', '[in_br]', 'Feet', 'ft');
INSERT INTO `units_of_measurement` (`id`, `name`, `kind_of_quantity`, `print`, `cs`, `ci`, `M`, `definition_value`, `definition_unit`, `IMS_name`, `IMS_code`) VALUES (5, 'Kilowatt', 'power', 'kW', 'kW', 'KW', 'yes', '1', 'J/s', 'Kilowatt', 'KW');
INSERT INTO `units_of_measurement` (`id`, `name`, `kind_of_quantity`, `print`, `cs`, `ci`, `M`, `definition_value`, `definition_unit`, `IMS_name`, `IMS_code`) VALUES (6, 'Horsepower', 'power', 'hp', '[HP]', '[HP]', 'no', '550', '[ft_i].[lbf_av]/s', 'Horsepower', 'HP');
INSERT INTO `units_of_measurement` (`id`, `name`, `kind_of_quantity`, `print`, `cs`, `ci`, `M`, `definition_value`, `definition_unit`, `IMS_name`, `IMS_code`) VALUES (7, 'Pound per Sqare Inch', 'pressure', 'psi', '[psi]', '[PSI] ', 'no', '1', '[lbf_av]/[in_i]2 ', 'PSI', 'PS');
INSERT INTO `units_of_measurement` (`id`, `name`, `kind_of_quantity`, `print`, `cs`, `ci`, `M`, `definition_value`, `definition_unit`, `IMS_name`, `IMS_code`) VALUES (8, 'tonne', 'mass', 't', 't', 'TNE', 'yes', '1 × 10^3', 'kg', 'tonne', 't');
INSERT INTO `units_of_measurement` (`id`, `name`, `kind_of_quantity`, `print`, `cs`, `ci`, `M`, `definition_value`, `definition_unit`, `IMS_name`, `IMS_code`) VALUES (9, 'kilogram', 'mass', 'kg', 'kg', 'KG', 'Yes', '1 × 10^3', 'g', 'kilogram', 'kg');
