INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('AS', 'USA (AMERICAN SAMOA)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('AU', 'AUSTRALIA', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('CK', 'COOK ISLANDS', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('CN', 'CHINA', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('FJ', 'FIJI', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('FM', 'FEDERATED STATES OF MICRONESIA', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('GL', 'GILBERT ISLANDS (KIRIBATI)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('GU', 'USA (GUAM)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('H4', 'International waters between Tuvalu, Phoenix and Tokelau, from the equator down to 10°S and east of 175°E to 170°W', 'BROWN');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('H5', 'International waters between Phoenix and Line Groups, from the equator down to 10°S, east of 170°W to 155°W (excludes IW between CK and PF = Area "I9")', 'IRIDESCENT GREEN');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('HB', 'USA (HOWLAND AND BAKER)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('HW', 'USA (HAWAII)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('I1', 'Doughnut hole between PNG and FSM', 'BLUE');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('I2', 'Doughnut hole between FSM, Solomons, Kiribati, Marshall Is. Nauru, Tuvalu', 'RED');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('I3', 'International waters east of the Philippines to Guam, above FSM, around Marshalls, up to 20°N and west of 175°E (not including areas I1, I2 and I8)', 'DARK GREEN');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('I4', 'International waters east of Marshall Islands and Kiribati, from the equator up to 20°N and east of 175°E to 170°W', 'ORANGE');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('I5', 'International waters around Line Group from the equator up to 20°N, east of 170°W to 150°W, and south of the equator to 20°S from 155°W-130°W', 'CRIMSON');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('I6', 'The reminder of International waters not covered above in the Northern hemisphere of the WCP-CA', 'LIGHT BLUE');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('I7', 'The reminder of International waters not covered above in the Southern hemisphere of the WCP-CA', 'LIGHT GREEN');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('I8', 'International waters bordered by Fiji, Solomon Is and Vanuatu', 'PURPLE');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('I9', 'International waters between the Cook Islands and French Polynesia', 'YELLOW');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('ID', 'INDONESIA', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('JP', 'JAPAN', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('JT', 'USA (JOHNSTON)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('JV', 'USA (JARVIS)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('KI', 'KIRIBATI', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('KR', 'REPUBLIC OF KOREA', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('LN', 'LINE ISLANDS (KIRIBATI)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('MA', 'MATTHEW AND HUNTER (DISPUTED: FR & VU)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('MH', 'MARSHALL ISLANDS', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('MP', 'NORTHERN MARIANA ISLANDS', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('NC', 'FRANCE (NEW CALEDONIA)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('NF', 'NORFOLK (AUSTRALIA)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('NR', 'NAURU', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('NU', 'NIUE', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('NZ', 'NEW ZEALAND', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('PF', 'FRANCE (FRENCH POLYNESIA)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('PG', 'PAPUA NEW GUINEA', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('PH', 'PHILIPPINES', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('PN', 'PITCAIRN', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('PW', 'PALAU', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('PX', 'PHOENIX (KIRIBATI)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('PY', 'USA (PALMYRA)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('SB', 'SOLOMON ISLANDS', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('TK', 'TOKELAU', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('TO', 'TONGA', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('TV', 'TUVALU', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('TW', 'CHINESE TAIPEI', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('US', 'UNITED STATES OF AMERICA', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('VU', 'VANUATU', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('WF', 'FRANCE (WALLIS AND FUTUNA)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('WK', 'USA (WAKE)', '');
INSERT INTO "authorised_fishing_areas" ("Code", "Description", "Color") VALUES ('WS', 'SAMOA', '');
